apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  labels:
    app: www
spec:
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: php-apache
        image: bzeitouni/projet_poei_final_tgv_www:1.1
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: www-service
  labels:
    run: www-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: www
