apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  labels:
    app: php-apache
spec:
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: bzeitouni/projet_poei_final_tgv_www:1.1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: www
  labels:
    app: php-apache
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: php-apache
